spring.application.name=AuthService
server.port=8089
spring.datasource.url=jdbc:postgresql://localhost:5433/userservicedb
spring.datasource.username=postgres
spring.datasource.password=nityam
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.config.import=optional:configserver:http://localhost:9999/config

# Logging Configuration
logging.file.path=logs
logging.file.max-size=10MB
logging.file.max-history=30
logging.level.root=INFO
logging.level.com.omnicharge.authservice=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.org.hibernate=WARN