spring.application.name=OperatorPlanManagement

server.port=8086

spring.datasource.url= jdbc:postgresql://localhost:5433/operatorPlan
spring.datasource.username=postgres
spring.datasource.password=aditya
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.cache.type = redis
spring.redis.host= localhost
spring.redis.port= 6379
#spring.cache.redis.time-to-live=60000

spring.config.import=optional:configserver:http://localhost:9999/config


# Logging Configuration
logging.file.path=logs
logging.file.max-size=10MB
logging.file.max-history=30
logging.level.root=INFO
logging.level.com.oprationPlanManagement=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.cache=INFO
logging.level.org.hibernate=WARN

