spring.application.name=EurekaServer
server.port=8761

# ================= EUREKA SERVER =================
# Prevent self-registration
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ================= ACTUATOR =================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

# ================= ZIPKIN / TRACING =================
# Sample 100% of requests (use 0.1 for 10% in production)
management.tracing.sampling.probability=1.0
# Zipkin server URL
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
# Enable tracing
management.tracing.enabled=true

# ================= LOGGING =================
logging.level.org.springframework.cache=TRACE
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
logging.file.path=logs
logging.file.max-size=10MB
logging.file.max-history=30
logging.level.root=INFO
logging.level.com.omnicharge=INFO
logging.level.org.springframework.web=INFO