spring.application.name=notificationservice
server.port=8085
# RabbitMQ Config
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hiddenakshat@gmail.com
spring.mail.password=buiu bshn hxtk qnwl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.config.import=optional:configserver:http://localhost:9999/config


twilio.accountSid=here
twilio.authToken=here
twilio.whatsappNumber=whatsapp:+14155238886

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

# Logging Configuration
logging.file.path=logs
logging.file.max-size=10MB
logging.file.max-history=30
logging.level.root=INFO
logging.level.com.omnicharge.notification=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.amqp=INFO
logging.level.org.springframework.mail=INFO
logging.level.com.twilio=INFO