spring.application.name=PaymentService
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5433/paymentservicedb
spring.datasource.username=postgres
spring.datasource.password=nityam
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.config.import=optional:configserver:http://localhost:9999/config

razorpay.key.id=rzp_test_SSyxB6jBd3fVby
razorpay.key.secret=A3sqaIh6v71g26xsDWS6WCbC
razorpay.webhook.secret=3B9bAMOJfGP5AM9rQ2J2rxuSTf5_4ebm15FUZWriJhKGEUuyH

# Resilience4J - Enable Feign circuit breaker integration
spring.cloud.openfeign.circuitbreaker.enabled=true

# Default circuit breaker config (applies to all Feign clients)
resilience4j.circuitbreaker.instances.default.sliding-window-size=10
resilience4j.circuitbreaker.instances.default.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.default.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.default.permitted-number-of-calls-in-half-open-state=5
resilience4j.circuitbreaker.instances.default.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.default.minimum-number-of-calls=5

# Actuator - expose circuit breaker health and events
management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true



# Retry for calls to OPERATORPLANMANAGEMENT
resilience4j.retry.instances.OPERATORPLANMANAGEMENT.max-attempts=3
resilience4j.retry.instances.OPERATORPLANMANAGEMENT.wait-duration=2s
resilience4j.retry.instances.OPERATORPLANMANAGEMENT.enable-exponential-backoff=true
resilience4j.retry.instances.OPERATORPLANMANAGEMENT.exponential-backoff-multiplier=2
resilience4j.retry.instances.OPERATORPLANMANAGEMENT.retry-exceptions=java.io.IOException,feign.FeignException

# Retry for calls to RECHARGEPROCESSING
resilience4j.retry.instances.RECHARGEPROCESSING.max-attempts=3
resilience4j.retry.instances.RECHARGEPROCESSING.wait-duration=2s
resilience4j.retry.instances.RECHARGEPROCESSING.enable-exponential-backoff=true
resilience4j.retry.instances.RECHARGEPROCESSING.exponential-backoff-multiplier=2
resilience4j.retry.instances.RECHARGEPROCESSING.retry-exceptions=java.io.IOException,feign.FeignException

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Logging Configuration
logging.file.path=logs
logging.file.max-size=10MB
logging.file.max-history=30
logging.level.root=INFO
logging.level.com.omnicharge.paymentservice=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.org.hibernate=WARN
