spring.application.name=APIGateway
server.port=8087

spring.config.import=optional:configserver:http://localhost:9999/config

spring.main.web-application-type=reactive

spring.cloud.gateway.server.webflux.routes[0].id=USERMANAGEMENT
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USERMANAGEMENT
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webflux.routes[1].id=RECHARGEPROCESSING
spring.cloud.gateway.server.webflux.routes[1].uri=lb://RECHARGEPROCESSING
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/recharge/**

spring.cloud.gateway.server.webflux.routes[2].id=PAYMENTSERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PAYMENTSERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/transaction/**

spring.cloud.gateway.server.webflux.routes[3].id=OPERATORPLANMANAGEMENT
spring.cloud.gateway.server.webflux.routes[3].uri=lb://OPERATORPLANMANAGEMENT
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/operators/**,/plans/**


spring.cloud.gateway.server.webflux.routes[4].id=AUTHSERVICE
spring.cloud.gateway.server.webflux.routes[4].uri=lb://AUTHSERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/auth/**

# Logging Configuration
logging.file.path=logs
logging.file.max-size=10MB
logging.file.max-history=30
logging.level.root=INFO
logging.level.com.omnicharge.apigateway=INFO
logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.security=INFO
logging.level.io.jsonwebtoken=INFO
