spring.application.name=UserManagement
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/userservicedb
spring.datasource.username=postgres
spring.datasource.password=nityam
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.config.import=optional:configserver:http://localhost:9999/config

# Logging Configuration
logging.file.path=logs
logging.file.max-size=10MB
logging.file.max-history=30
logging.level.root=INFO
logging.level.com.omnicharge.usermanagement=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.cache=INFO
logging.level.org.hibernate=WARN

logging.level.io.micrometer.tracing=DEBUG
logging.level.io.opentelemetry=DEBUG

# Zipkin & Distributed Tracing Configuration
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.zipkin.tracing.connect-timeout=5000
management.zipkin.tracing.read-timeout=5000

# Enable micrometer tracing
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.export.prometheus.enabled=true


logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# Additional tracing configuration for Spring Boot 4.0.3
management.tracing.enabled=true
management.observations.enable.http.server.requests=true
management.observations.enable.http.client.requests=true
