spring.application.name=UserManagement
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/userservicedb
spring.datasource.username=postgres
spring.datasource.password=nityam
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


spring.config.import=optional:configserver:http://localhost:9999/config
